


Cleaning up School Info Data
```{r}
library(dplyr)
library(stringr)
```

Read in the schools list to get school information
```{r}
# read in the school info csv file
schools <- read.csv("data/school_info/school_info.csv",header = TRUE)

# extract the info we want
s_col_names <- c('UNITID','school_name','year','int_name','address','city','state')
colnames(schools) <- s_col_names
schools$address <- paste(schools$address,schools$city,sep=", ")
schools$address <- paste(schools$address,schools$state,sep=", ")
schools <- schools |> select(c('UNITID','school_name','address','state'))

str(schools)
```

Read in d1 schools list 
```{r}
# read in the file
d1_schools <- read.csv('UNITID_school_names.csv',header = TRUE)

# reduce to two columns to later merge with financial data
d1_schools <- d1_schools |> select('d1_id','UNITID')
str(d1_schools)
```


Create readable dictionary with new variables
```{r}

# vars <- c("UNITID","F1A01","F1D01",'F1D02','F1B01','F1B02','F1B03','F1B04','F1B04A','F1B04B','F1B05',
# 'F1B10','F1B11','F1B12','F1B13','F1B14','F1B15','F1B16','F1B21','F1B23','F1B24','F1B25','F1C021','F1C022','F1C101','F1E01','F1E02','F1E03','F1E04','F1E05','F1E06','F1E07','F1E08','F1E10','F1E11','F1E12','F1E121','F1E122','F1E13','F1E131','F1E132','F1E14','F1E141','F1E142','F1E15','F1E151','F1E152','F1E16','F1E161','F1H03A')

# list of all the variables we care about
vars <- c("UNITID",'F1A01', 'F1B16', 'F1B21', 'F1C021', 'F1E08')

# read the dictionary file and dictionary description files
v_file <- read.csv('data/data_dictionaries/raw_dicts/fin_dict_vars.csv', header = TRUE)
d_file <- read.csv('data/data_dictionaries/raw_dicts/fin_dict_desc.csv', header = TRUE)
# merge the descritpion and variable names
dict <- merge(v_file,d_file,by = 'varname')
# select only the variables we are going to be looking at
dict <- dict |> select(c("varname","varTitle","longDescription")) |> subset(varname %in% vars) 
#str(dict)
list <- dict |> select(c("varname","varTitle"))
#write to CSVs
write.csv(dict,"data/data_dictionaries/fin_sub_dict.csv", row.names = FALSE)
write.csv(list,"data/data_dictionaries/fin_sub_dict_list.csv", row.names = FALSE)
```

Create Function to read files
```{r}
load_fin_data <- function(f) {
    # load the file
    file <- read.csv(f, header = TRUE)

    # remove all the columns that contain indicator variables
    file <- file |> select(-contains("X"))

    # select only the columns that are in the chosen variable list, vars
    df <- file |> select(all_of(vars))
    # merge with schools to get all the school info
    df <- merge(x = df, y = schools, by = "UNITID", all.x=TRUE)
    df <- df |> relocate(c(school_name,address,state), .after=UNITID)

    # rename the columns
    colnames(df) <- c("UNITID","school_name","address","state","total_assets","gifts","capital_grants_gifts","research_spent","discounts_to_tuiton")

    # merge with d1 schools list
    df_d1 <- merge(d1_schools, df, by="UNITID", all.x = TRUE) |> arrange(d1_id)

    # create the file name
    year <- str_sub(f,-10,-9)
    new_f <- 'data/clean_fin_data/20'
    end <- "_fin_data.csv"
    new_f <- paste(new_f,year,end,sep="")

    str(df_d1)

    #write to csv
    write.csv(df_d1,new_f,row.names = FALSE)
    print("done")
}
```


```{r}
f = "data/raw_fin_data/f1718_f1a.csv"

file <- read.csv(f, header = TRUE)

# remove all the columns that contain indicator variables
file <- file |> select(-contains("X"))

# select only the columns that are in the chosen variable list, vars
df <- file |> select(all_of(vars))
# merge with schools to get all the school info
df <- merge(x = df, y = schools, by = "UNITID", all.x=TRUE)
df <- df |> relocate(c(school_name,address,state), .after=UNITID)

# rename the columns
colnames(df) <- c("UNITID","school_name","address","state","total_assets","gifts","capital_grants_gifts","research_spent","discounts_to_tuiton")

# merge with d1 schools list
df_d1 <- merge(d1_schools, df, by="UNITID", all.x = TRUE) |> arrange(d1_id)

# create the file name
year <- str_sub(f,-10,-9)
new_f <- 'data/clean_fin_data/20'
end <- "_fin_data.csv"
new_f <- paste(new_f,year,end,sep="")

str(df_d1)

#write to csv
write.csv(df_d1,new_f,row.names = FALSE)
print("done")


```

Read files
```{r}
#find all tifs in your directory
dir <-"data/raw_fin_data"
#get a list of all files with ndvi in the name in your directory
files<-list.files(path=dir, full.names = TRUE)
#print(files)
for (f in files){
    print(f)
    load_fin_data(f)
}
```