project:
  type: website

website:
  title: "DSAN 5100 Final Presentation - Group 7"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - slides/slides.qmd

format:
  html:
    theme: cosmo
    toc: true
